services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: sentinel_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rohit
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d sentinel_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:rohit@db:5432/sentinel_db
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=rohit
      - DB_NAME=sentinel_db
    depends_on:
      db:
        condition: service_healthy